config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  get "/registration", action: "create", controller: "registration"
  get "/login", action: "new", controller: "session"
  post "/login", action: "create", controller: "session"
  resources :users, only: %i[new create show]
end

app/models/account_activate.rb
class AccountActivate < ApplicationRecord
  belongs_to :user

  validates :certificated_at, presence: true

  before_validation :ensure_certificated_at

  private

  def ensure_certificated_at
    self.certificated_at = Time.zone.now
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/social_account.rb
class SocialAccount < ApplicationRecord
  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :uid, presence: true, uniqueness: true

  has_many :user_social_accounts
  has_many :users, through: :user_social_accounts
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :email, presence: true, uniqueness: { case_sensitive: false }
  has_secure_password

  has_many :user_social_accounts, dependent: :destroy
  has_many :social_accounts, through: :user_social_accounts, dependent: :destroy
  has_one  :account_activate

  def activate?
    return false unless account_activate
    true
  end

  def activate
    create_account_activate
  end

  def self.find_from_token(token)
    return nil unless token
    verifier = Rails.application.message_verifier(:registration_user)
    return nil unless verifier.valid_message?(token)
    id, registrated_at = verifier.verify(token)
    return nil if registrated_at < 1.day.ago
    User.find_by(id: id)
  end

  def verifier_token
    verifier = Rails.application.message_verifier(:registration_user)
    verifier.generate([id, Time.zone.now])
  end

  def send_email
    UserMailer.account_activation(self, verifier_token).deliver_now
  end
end

app/models/user_social_account.rb
class UserSocialAccount < ApplicationRecord
  belongs_to :user
  belongs_to :social_account
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/registration_controller.rb
class RegistrationController < ApplicationController
  def create
    @user = User.find_from_token(params[:token])
    redirect_to new_user_path unless @user
    if @user.activate
      redirect_to @user
    else
      redirect_to new_user_path
    end
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  before_action :set_user, only: :create

  def new; end

  def create
    if @user&.authenticate(session_params[:password])
      session[:user_id] = @user.id
      redirect_to @user
    else
      render :new
    end
  end

  def destroy
    logout
  end

  private

  def session_params
    params.require(:session).permit(
      :name,
      :password
    )
  end

  def set_user
    @user = User.find_by(name: session_params[:name])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.send_email
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :name,
      :email,
      :self_introduction,
      :profile_image,
      :password,
      :password_confirmation
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def user_signed_in?
    current_user.present?
  end

  def login(user)
    session[:user_id] = user.id
  end

  def logout
    session.delete(:user_id)
    @current_user = nil
  end
end

app/views/home/index.html.haml
%p Hello world

app/views/layouts/_header.html.haml
.top-header
  %ul.menu
    %li
      = link_to("Eatwit", root_path)
    %li
      - if user_signed_in?
        = link_to(current_user.name, user_path(current_user))
      - else
        = link_to("ログイン", new_user_path)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ :content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type" }/
    %title Eatwit
    = csrf_meta_tags
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track": "reload"
    = javascript_include_tag "application", "data-turbolinks-track": "reload"
  %body
    = render "layouts/header"
    = yield

app/views/session/new.html.haml
.form
  = form_for(:session, url: login_path) do |f|
    = f.label :name
    .input
      = f.text_field :name
    = f.label :password
    .input
      = f.password_field :password
    = f.submit class: "button"

app/views/users/new.html.haml
.form
  = form_for @user do |f|
    - if @user.errors
      .box
        - @user.errors.full_messages.each do |message|
          %li= message
    = f.label :name
    .input
      = f.text_field :name
    = f.label :email
    .input
      = f.text_field :email
    = f.label :password
    .input
      = f.password_field :password
    = f.label :password_confirmation
    .input
      = f.password_field :password_confirmation
    = f.submit class: "button"